#!/bin/bash

###########
# Install software
###########

printf "\n\nUpdating, upgrading APT...\n"
echo "________________"
sudo apt update
sudo apt upgrade -y

printf "\n\nInstalling Apt software...\n"
echo "________________"
sudo apt install -y \
#!/bin/bash
    vim-gtk3 \
    tmux \
	gdb \
    xclip \
    curl \
    cmake \
    tofrodos \
    build-essential \
    python3-dev \
    aptitude \
    snap \
    tree \
    trash-cli \
    grub-customizer

sudo snap install mediainfo


printf "\n\nCopying, sourcing .bash_aliases...\n"
echo "________________"
cp files/.bash_aliases /home/$USER/.bash_aliases
. /home/$USER/.bashrc

printf "\n\nRemoving unnecessary Apt files...\n"
echo "________________"
sudo apt autoremove -y

#############
# Copy configuration files
#############

printf "\n\n"
printf "Copying configuration files and scripts...\n"
echo "________________"

printf "jvalcher (sudoers.d)\n"
sudo cp files/jvalcher /etc/sudoers.d/jvalcher

echo ".tmux.conf"
cp files/.tmux.conf /home/$USER/

echo ".gdbinit"
cp files/.gdbinit /home/$USER/

echo ".gitconfig"
cp files/.gitconfig /home/$USER/

printf "~/bin...\n"
BIN_DIR="/home/$USER/bin"
if [ ! -d $BIN_DIR ]; then
    mkdir $BIN_DIR
    cp files/bin_cli/* $BIN_DIR/
else
    rsync -a --delete files/bin_cli/ $BIN_DIR/
fi

printf "singing_bowl.wav\n"
cp files/singing_bowl.wav /home/$USER/Music/

echo ".vimrc"
cp files/.vimrc /home/$USER/.vimrc


#####################
# vim configuration #
#####################

printf "\n\n"
printf "Configuring vim...\n"
echo "________________"

VIM_DIR="/home/$USER/.vim"

echo "skeletons..." 
echo "________________"
VIM_DIR="/home/$USER/.vim"
if [ -e $VIM_DIR/skeletons ]; then
    rsync -a --delete files/skeletons/ /home/$USER/.vim/skeletons/
else 
    cp -r files/skeletons $VIM_DIR/
fi

echo "vim-superman..." 
if [ -d $VIM_DIR/bundle/vim-superman ]; then
    git clone https://github.com/jez/vim-superman ~/.vim/bundle/vim-superman
fi

echo "vundle plugins..." 
vim -c 'PluginInstall' -c 'qa!'

echo "vim-plug plugins..." 
vim -c 'PlugInstall' -c 'qa!'

. /home/$USER/.bashrc


################
# Exit message #
################

printf "\n\n\n"
echo "________________"
printf "Provisioning complete\n"
echo "________________"
printf "\n\n"


