#!/bin/bash

###########
# Install software
###########

printf "\n\nInstalling Apt software...\n"
echo "________________"
sudo apt update
sudo apt upgrade -y

sudo apt-get install -y \
#!/bin/bash
    vim-gtk3 \
    tmux \
    xclip \
    curl \
    cmake \
    build-essential \
    python3-dev \
    aptitude \
    tree \
    grub-customizer


printf "\n\nCopying, sourcing .bash_aliases...\n"
echo "________________"
cp files/.bash_aliases /home/$USER/.bash_aliases
. /home/$USER/.bashrc

printf "\n\nRemoving unnecessary Apt files...\n"
echo "________________"
sudo apt autoremove -y

#############
# Copy configuration files
#############

printf "\n\n"
printf "Copying configuration files and scripts...\n"
echo "________________"

printf "jvalcher \t\t(sudoers.d)\n"
sudo cp files/jvalcher /etc/sudoers.d/jvalcher

echo ".tmux.conf"
cp files/.tmux.conf /home/$USER/

printf "~/bin...\n"
sudo cp -r files/cli/bin /home/$USER/

echo ".vimrc"
cp files/.vimrc /home/$USER/.vimrc

#####################
# vim configuration #
#####################

printf "\n\n"
printf "Configuring vim...\n"
echo "________________"

VIM_DIR="/home/$USER/.vim"

echo "skeletons..." 
echo "________________"
VIM_DIR="/home/$USER/.vim"
if [ -e $VIM_DIR/skeletons ]; then
    rsync -a --delete files/skeletons/ /home/$USER/.vim/skeletons/
else 
    cp -r files/skeletons $VIM_DIR/
fi

echo "vim-superman..." 
if [ -d $VIM_DIR/bundle/vim-superman ]; then
    git clone https://github.com/jez/vim-superman ~/.vim/bundle/vim-superman
fi

echo "vundle plugins..." 
vim -c 'PluginInstall' -c 'qa!'

echo "YouCompleteMe..." 
(cd $VIM_DIR/bundle/YouCompleteMe && python3 install.py --clangd-completer)

echo "vim-plug plugins..." 
vim -c 'PlugInstall' -c 'qa!'


################
# Exit message #
################

printf "\n\n\n"
echo "________________"
printf "Provisioning complete\n"
echo "________________"
printf "\n\n"


