#!/bin/bash

###########
# Install software
###########

printf "\n\nInstalling Apt software...\n"
echo "________________"
sudo apt update
sudo apt upgrade -y

sudo apt-get install -y \
#!/bin/bash
    vim-gtk3 \
    tmux \
    xclip \
    curl \
    cmake \
    build-essential \
    python3-dev \
    aptitude \
    tree \

printf "\n\nCopying, sourcing .bash_aliases...\n"
echo "________________"
cp files/.bash_aliases /home/$USER/.bash_aliases
. /home/$USER/.bashrc

printf "\n\nRemoving unnecessary Apt files...\n"
echo "________________"
sudo apt autoremove -y

#############
# Copy configuration files
#############

printf "\n\n"
printf "Copying configuration files and scripts...\n"
echo "________________"

sudo cp files/jvalcher /etc/sudoers.d/jvalcher
printf "jvalcher \t\t(sudoers.d)\n"

cp files/.vimrc /home/$USER/.vimrc
echo ".vimrc"

cp -r files/Scripts /home/$USER/
printf "~/Scripts...\n"

sudo cp -r files/bin /home/$USER/
printf "~/bin...\n"

cp files/gtk.css /home/$USER/.config/gtk-3.0/gtk.css
echo "gtk.css"

cp files/.tmux.conf /home/$USER/
echo ".tmux.conf"

cp files/singing_bowl.wav /home/$USER/Music/
printf "singing_bowl.wav\n"

VIM_DIR="/home/$USER/.vim"
printf "\n\n"
printf "Copying Vim skeletons...\n"
echo "________________"
if [ -e $VIM_DIR/skeletons ]; then
    rsync -a --delete files/skeletons/ /home/$USER/.vim/skeletons/
else
    cp -r files/skeletons $VIM_DIR/skeletons
fi

##########
# Exit message
##########

printf "\n\n\n"
echo "________________"
printf "Provisioning complete\n"
echo "________________"
printf "\n\n"


