#!/bin/bash


##################
# Interval Timer #
##################

# Usage:   workout 35
# Press 'q' or ctrl-C to exit
# Uses figlet to display numbers
# Uses cvlc to play sounds (VLC)


# interval sound
SOUND="/home/jvalcher/Music/correct_bing.mp3"


# center text vertically
function center_vertically ()
{
    # number of lines in current terminal
    TOT_LINES=$(tput lines)

    # number of lines to skip 
    NUM_LINES=$(( TOT_LINES / 3 ))
    
    # while NUM_LINES is greater than 0...
    while [ $NUM_LINES -gt 0 ]
    do
        # print new line
        echo ""

        # subtract line
        NUM_LINES=$(( NUM_LINES - 1 ))

    done
}

# exit program
function quit () 
{
    # return cursor
    tput cnorm 

    clear
    exit 0
}

# countdown timer
function timer_loop() 
{
    # set duration to first argument
    SECS=$1

    # while SECS is greater than 0...
    while [ $SECS -ge 0 ]
    do

        # print second
        clear
        printf "\n   Press 'q' to quit"
        center_vertically
        figlet -f big -k -c -r $SECS

        # 1-second timeout to store single-character
        read -t 1 -N 1 INPUT

        # run quit if 'q' pressed
        if [[ $INPUT = "q" ]]; then
            quit
        fi

        # run quit if ctrl-C pressed
        function trap_ctrlc () {
            quit
        }
        trap "trap_ctrlc" 2

        # subtract second
        SECS=$(( SECS -1 ))

    done
    
    # play sound
    cvlc $SOUND > /dev/null 2>&1 &
}


# check if argument supplied
if [ $# -eq 0 ]; then
    printf "\nUsage: \n\tworkout <seconds>\n\n"
    exit 1;
fi


# turn off cursor
tput civis


# 5-second countdown to start
clear
center_vertically
figlet -f big -k -c -r "Get Ready..."
sleep 5
cvlc $SOUND > /dev/null 2>&1 &


# set interval duration in seconds to first command line argument
INTERVAL=$1

# repeat timer indefinitely
while true; do

    timer_loop $INTERVAL

done



## Create workout session
#
## print current, next exercise
#function print_exercise() {
#    EXERCISE=$1;
#    NEXT=$2;
#    printf "\e[1;33m$EXERCISE\e[0m\n\n"
#    printf "\e[1;32mnext: $NEXT\e[0m\n\n"
#}
#
#print_exercise "Jumping Jacks" "Right Torso Stretch"
#timer_loop 60
#print_exercise "Right Torso Stretch" "Left Torso Stretch"
#timer_loop 30
#print_exercise "Left Torso Stretch" "Squats"
#timer_loop 30
#print_exercise "Squats" "Down Stretch"
#timer_loop 30
